version: '3'
services:
  postgres:
    container_name: chatwoot_postgres
    image: postgres:14
    environment:
      POSTGRES_DB: chatwoot_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: chatwoot_redis
    image: redis:6
    ports:
      - "6379:6379"
    command: redis-server --requirepass chatwoot
    volumes:
      - redis_data:/data

  mailhog:
    container_name: chatwoot_mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  default:
    name: chatwoot_network

volumes:
  postgres_data:
  redis_data:
